apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpm-deployment
  labels:
    app: fpm
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: fpm
  template:
    metadata:
      labels:
        app: fpm
    spec:
      containers:
        - name: fpm
          imagePullPolicy: Always
          image: ktsivkov/local-fpm:latest
          ports:
            - containerPort: 9000
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - '-c'
                  - sleep 10
      terminationGracePeriodSeconds: 30
